name: etcd
adopt-info: etcd-version
summary: Distributed reliable key-value store
description: |
  Etcd is a high availability key-value store, implementing the Raft
  algorithm to deal with failover within the etcd cluster. Popular
  as a store of small but important data in distributed systems.
confinement: strict
grade: stable
base: core22

architectures:
  - build-on: [amd64]
  - build-on: [arm64]
  - build-on: [s390x]

apps:
  etcd:
    daemon: simple
    command: bin/snap-wrap.sh
    plugs: [ network-bind, removable-media ]
  etcdctl:
    command: bin/etcdctl
    plugs: [ home, network-bind ]

parts:
  etcd:
    plugin: go
    build-snaps:
    - go/1.24/stable
    source: http://github.com/etcd-io/etcd.git
    source-tag: v3.5.22
    override-build: |
      ./build.sh
      mkdir -p $CRAFT_PART_INSTALL/bin
      mv $CRAFT_PART_BUILD/bin/* $CRAFT_PART_INSTALL/bin/
  etcd-wrapper:
    plugin: dump
    source: .
    stage:
    - bin/snap-wrap.sh
    - etcd.conf.yml.sample
  etcd-version:
    after: [etcd]
    plugin: nil
    source: .
    override-prime: |
      etcd_version=$($CRAFT_PRIME/bin/etcdctl version | grep -i 'etcdctl version' | awk '{print $3}')
      craftctl set version="$etcd_version"
