name: etcd
version: '3.2.32'
summary: Resilient key-value store by CoreOS
description: |
  Etcd is a high availability key-value store, implementing the Raft
  algorithm to deal with failover within the etcd cluster. Popular
  as a store of small but important data in distributed systems.
confinement: strict
grade: stable
base: core18
 
# pending a fix to snapd environment variable handling
# environment:
#   ETCDCTL_API: 3

apps:
  etcd:
    daemon: simple
    command: snap-wrap.sh
    plugs: [ network-bind, removable-media ]
  etcdctl:
    command: etcdctl
    plugs: [ home, network-bind ]

# You might be curious as to why we had to install golang from ppa instead of
# using the go part in snapcraft like we used to
# (https://github.com/juju-solutions/etcd-snaps/blob/v3.1/snap/snapcraft.yaml#L28)
# Everything started failing after this upstream
# PR: https://github.com/coreos/etcd/commit/b1e87f8ae1b4629cc07ade4fbe12caa4401b8a34
# Upstream practically killed the vendored build on the v3.2 branch.
# Here is the issue opened upstream telling them the vendored build is
# failing https://github.com/coreos/etcd/issues/9928
# On our v3.2 branch as soon as you fix the moved paths
# (as we do in this PR on the master https://github.com/juju-solutions/etcd-snaps/pull/13/files)
# the libs & version you get on xenial are not the correct ones so the go plugin fails.
# Practically we would be chasing after dependencies and versions

parts:
  etcd:
    plugin: dump
    source: .
    override-build: |
      set -eux
      mkdir -p gopath
      mkdir -p gopath
      apt-get -y install software-properties-common
      add-apt-repository ppa:gophers/archive
      apt-get update
      apt-get install git golang-1.10-go -y
      export PATH=$PATH:/usr/lib/go-1.10/bin
      export SNAP_ROOT="$(readlink -f .)"
      export GOPATH=$SNAP_ROOT/gopath
      git clone https://github.com/coreos/etcd.git -b v3.2.32 --depth 1
      (cd etcd; ./build)
      cp -r ./etcd/bin ../install
      chmod +x ./etcd/bin/etcd
      chmod +x ./etcd/bin/etcdctl

  etcd-wrapper:
    plugin: dump
    source: .
    stage:
      - bin/snap-wrap.sh
      - etcd.conf.yml.sample
