name: etcd
version: '3.2.9'
summary: Resilient key-value store by CoreOS
description: |
  Etcd is a high availability key-value store, implementing the RAFT
  algorithm to deal with failover within the etcd cluster. Popular
  as a store of small but important data in distributed systems.
confinement: strict
grade: stable

# pending a fix to snapd environment variable handling
# environment:
#   ETCDCTL_API: 3

apps:
  etcd:
    daemon: simple
    command: snap-wrap.sh
    plugs: [ network-bind, removable-media ]
  etcdctl:
    command: etcdctl
    plugs: [ home, network-bind ]
    aliases:
      - etcdctl

parts:
  go:
    source-tag: go1.8.4
  etcd:
    source: http://github.com/coreos/etcd.git
    source-tag: v3.2.9
    plugin: go
    go-importpath: github.com/coreos/etcd
    go-packages:
      - github.com/coreos/etcd/cmd/etcd
      - github.com/coreos/etcd/cmd/etcdctl
    after: [go]
  etcd-wrapper:
    plugin: dump
    source: .
    stage:
      - bin/snap-wrap.sh
      - etcd.conf.yml.sample
