name: etcd
version: '3.4.35'
summary: Distributed reliable key-value store
description: |
  Etcd is a high availability key-value store, implementing the Raft
  algorithm to deal with failover within the etcd cluster. Popular
  as a store of small but important data in distributed systems.
confinement: strict
grade: stable
base: core18

apps:
  etcd:
    daemon: simple
    command: snap-wrap.sh
    plugs: [ network-bind, removable-media ]
  etcdctl:
    command: etcdctl
    plugs: [ home, network-bind ]

parts:
  etcd:
    plugin: go
    go-channel: 1.22/stable
    source: http://github.com/etcd-io/etcd.git
    source-tag: v3.4.35
    override-build: |
      go build -o $SNAPCRAFT_PART_INSTALL/bin/etcd go.etcd.io/etcd
      go build -o $SNAPCRAFT_PART_INSTALL/bin/etcdctl go.etcd.io/etcd/etcdctl
  etcd-wrapper:
    plugin: dump
    source: .
    stage:
      - bin/snap-wrap.sh
      - etcd.conf.yml.sample
