name: etcd
version: '3.2.10'
summary: Resilient key-value store by CoreOS
description: |
  Etcd is a high availability key-value store, implementing the RAFT
  algorithm to deal with failover within the etcd cluster. Popular
  as a store of small but important data in distributed systems.
confinement: strict
grade: stable

# pending a fix to snapd environment variable handling
# environment:
#   ETCDCTL_API: 3

apps:
  etcd:
    daemon: simple
    command: snap-wrap.sh
    plugs: [ network-bind, removable-media ]
  etcdctl:
    command: etcdctl
    plugs: [ home, network-bind ]
    aliases:
      - etcdctl

parts:
  etcd:
    plugin: dump
    source: .
    override-build: |
      set -eux
      mkdir -p gopath
      mkdir -p gopath
      apt-get -y install software-properties-common
      add-apt-repository ppa:gophers/archive
      apt-get update
      apt-get install golang-1.10-go -y
      export PATH=$PATH:/usr/lib/go-1.10/bin
      export SNAP_ROOT="$(readlink -f .)"
      export GOPATH=$SNAP_ROOT/gopath
      git clone https://github.com/coreos/etcd.git -b v3.2.10 --depth 1
      (cd etcd; ./build)
      cp -r ./etcd/bin ../install
      chmod +x ./etcd/bin/etcd
      chmod +x ./etcd/bin/etcdctl

  etcd-wrapper:
    plugin: dump
    source: .
    stage:
      - bin/snap-wrap.sh
      - etcd.conf.yml.sample
