name: Build Snap

# Controls when the action will run. Triggers the workflow on push to any branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - uses: jhenstridge/snapcraft-build-action@522a6a0433468c588c55e32d0e128c51b9b66b9d # v1
      id: snapcraft
    - name: Test snap
      run: sudo ./test_snap.sh ${{ steps.snapcraft.outputs.snap }}
    - uses: actions/upload-artifact@34622df80861c3ed63eb2bff892de2f1fbf4c9da # v1
      with:
        name: etcd.snap
        path: ${{ steps.snapcraft.outputs.snap }}
