name: Build Snap

# Controls when the action will run. Triggers the workflow on push to any branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - uses: canonical/action-build@v1
      id: snapcraft
      with:
        snapcraft-channel: 8.x/stable
    - name: Test snap
      run: sudo ./test_snap.sh ${{ steps.snapcraft.outputs.snap }}
    - uses: actions/upload-artifact@v4
      with:
        name: snap-built-by-${{ matrix.runner }}
        path: ${{ steps.snapcraft.outputs.snap }}
    - name: Setup tmate session
      if: failure()
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 10
