name: Build Snap

# Controls when the action will run. Triggers the workflow on push to any branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: snapcraft
      with:
        snapcraft-channel: 7.x/stable
    - name: Test snap
      run: sudo ./test_snap.sh ${{ steps.snapcraft.outputs.snap }}
    - uses: actions/upload-artifact@v4
      with:
        name: etcd.snap
        path: ${{ steps.snapcraft.outputs.snap }}
